import type { Locale } from "@modeltruth/i18n";
import { buildSeoMetadata, faqPageJsonLd, jsonLdScript } from "@modeltruth/seo";

export async function generateMetadata({
  params
}: {
  params: Promise<{ locale: Locale }>;
}) {
  const { locale } = await params;
  return buildSeoMetadata({
    locale,
    path: "/dispute",
    title: "Provider dispute policy | ModelTruth.ai",
    description:
      "How providers can submit corrections, request review and attach responses to ModelTruth technical audit results."
  });
}

export default function DisputePage() {
  return (
    <article className="card">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={jsonLdScript(
          faqPageJsonLd([
            {
              question: "Are ModelTruth results legal accusations?",
              answer:
                "No. Results are automated technical signals generated under specific test conditions."
            },
            {
              question: "How can a provider dispute a result?",
              answer:
                "Submit providerSlug, requestType, runId if available, contactEmail, statement and optional HTTPS evidenceUrl to /api/disputes."
            }
          ])
        )}
      />
      <div className="eyebrow">Dispute Policy</div>
      <h1>Providers may request review of technical audit results.</h1>
      <p className="lede">
        ModelTruth publishes evidence signals, confidence and retest recommendations. Providers can
        submit corrections or a response, and reviewed results may be marked under review, resolved
        or updated after review.
      </p>
      <p>
        Results are generated by automated technical tests at a specific time and under specific
        conditions. They are not legal conclusions, endorsements, or accusations of wrongdoing.
        Providers may submit corrections or dispute a result.
      </p>
      <div className="metricGrid">
        <div className="metric">1. Submit a correction, provider response or takedown request.</div>
        <div className="metric">2. Include run ID and supporting evidence.</div>
        <div className="metric">3. ModelTruth starts review or retest within 48 hours.</div>
        <div className="metric">4. Public status is updated after review.</div>
      </div>
      <div className="metricGrid legalGrid">
        <div className="metric">Public status: Active</div>
        <div className="metric">Public status: Under review</div>
        <div className="metric">Public status: Resolved</div>
        <div className="metric">Public status: Provider response attached</div>
      </div>
      <p className="lede">
        API endpoint: <code>POST /api/disputes</code> with <code>requestType</code> set to
        <code>correction</code>, <code>provider_response</code> or <code>takedown</code>. Email fallback:
        compliance@modeltruth.ai.
      </p>
    </article>
  );
}
