import type { Locale } from "@modeltruth/i18n";
import { faqPageJsonLd, buildSeoMetadata, jsonLdScript } from "@modeltruth/seo";

export async function generateMetadata({
  params
}: {
  params: Promise<{ locale: Locale }>;
}) {
  const { locale } = await params;
  return buildSeoMetadata({
    locale,
    path: "/terms",
    title: "Terms of service | ModelTruth.ai",
    description:
      "ModelTruth terms for technical AI API audit evidence, subscriptions and acceptable use."
  });
}

export default function TermsPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={jsonLdScript(
          faqPageJsonLd([
            {
              question: "Are ModelTruth results legal conclusions?",
              answer: "No. ModelTruth results are automated technical signals, not endorsements or accusations."
            },
            {
              question: "Who may submit endpoints for testing?",
              answer: "Users must have legal and contractual authority to test every endpoint, model id and API key they submit."
            }
          ])
        )}
      />
      <article className="card legalPage">
        <div className="eyebrow">Terms</div>
        <h1>Technical evidence for API buyers.</h1>
        <p className="lede">
          ModelTruth provides automated audit results, confidence scores and redacted
          evidence packages. Results are technical signals and do not constitute legal
          findings about any provider.
        </p>
        <section>
          <h2>Technical monitoring only</h2>
          <p>
            The service is provided for technical monitoring, reference and evidence organization.
            Results are generated by automated technical tests at a specific time and under
            specific conditions. They are not legal conclusions, endorsements or accusations of wrongdoing.
          </p>
        </section>
        <section>
          <h2>Authority to test</h2>
          <p>
            You must have the legal and contractual right to test every endpoint, Base URL, model id
            and API key you submit to ModelTruth. You are responsible for respecting provider terms,
            rate limits and access controls.
          </p>
        </section>
        <section>
          <h2>Acceptable use</h2>
          <ul>
            <li>Do not use ModelTruth for DDoS, pressure testing, credential stuffing or abuse.</li>
            <li>Do not use ModelTruth to bypass access controls, scrape private systems or test endpoints you do not control or have permission to test.</li>
            <li>ModelTruth may throttle, refuse or disable high-risk, unlawful or high-cost tests.</li>
            <li>Alerts are best-effort and are not guaranteed to arrive in real time.</li>
          </ul>
        </section>
        <section>
          <h2>Evidence and public content</h2>
          <p>
            Public pages may display aggregate metrics, suite versions, timestamps, assertion summaries,
            confidence and dispute status. ModelTruth may remove unlawful, infringing or high-risk public content.
            Providers may submit corrections or dispute a result through the Dispute Policy.
          </p>
        </section>
        <section>
          <h2>Liability limit</h2>
          <p>
            To the maximum extent permitted by law, ModelTruth liability is capped at the amount paid
            by the customer in the previous three months, or the minimum limit allowed by applicable law.
          </p>
        </section>
      </article>
    </>
  );
}
